In [1]:
import numpy as np

In [2]:
#Create a null vector of size 10 but the fifth value which is 1.
def function():
    arr = np.zeros(10, dtype = int)
    arr[4] = 1
    return arr
function()

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [4]:
#Create a vector with values ranging from 10 to 49.
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
 #Create a 3x3 matrix with values ranging from 0 to 9
    
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
nums = np.array([1,2,0,0,4,0])
print("original array")
print(nums)
print("indices of non zero elements  of the said array")
result =np.where(nums != 0)[0]
print(result)



In [13]:
#Create a 10x10 array with random values and find the minimum and maximum values.
x = np.random.random((10,10))
print(x)
xmax,xmin =x.max(),x.min()
print(xmax,xmin)

[[4.87182285e-01 8.49272269e-01 8.44872955e-01 1.33850784e-01
  7.30959927e-01 3.26166176e-01 5.09842722e-02 8.34241876e-01
  8.12062007e-01 1.44027224e-01]
 [4.24108743e-02 3.56063069e-01 3.71933942e-01 5.03974617e-01
  6.52455670e-01 6.84545736e-01 9.35416175e-01 1.76257080e-01
  2.56626093e-01 6.29495510e-01]
 [6.07137450e-01 6.30830862e-01 3.50442201e-01 2.69419689e-01
  1.82566598e-01 6.92487348e-01 6.02786435e-01 5.14957723e-01
  8.07391714e-01 5.94621116e-01]
 [3.14633894e-01 9.76044260e-01 9.26766905e-01 8.28210694e-01
  6.31247435e-02 5.02110249e-01 8.92507006e-01 1.60809886e-01
  6.45679817e-02 4.18830706e-01]
 [5.23645216e-01 5.54531211e-02 8.75442607e-02 6.50109315e-01
  4.09385790e-01 8.70674164e-01 7.61983246e-01 2.67908964e-01
  9.25709478e-01 3.22838797e-01]
 [4.65215723e-01 6.02392105e-01 3.80332469e-01 1.77912223e-01
  9.23233036e-01 7.56028725e-02 3.68027901e-01 9.99160689e-02
  1.86701507e-03 5.63979351e-01]
 [3.46140214e-01 3.02157326e-01 5.63850047e-01 4.41890754e

In [14]:
#Create a random vector of size 30 and find the mean value.
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5530020111616516
